### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#1]
Hi,
I have openKB installed and running ok. If I click on `login` and enter the first time email address and password the form appears to submit but just reappears if you click `login` again.

Any ideas?

**Comment by mrvautin** [comment]
What OS are you running?When you start up the app do you get any files being created in the data directory? The user starting the app needs write access to that directory for nedb data files.
    _____________________________

**Comment by thedaftbadger** [comment]
Running Windows and XAMPP with Nodejs also installed and running a few other apps. At the minute I set all users to have full access to the whole directory to see if that fixed anything.

**Comment by mrvautin** [comment]
FYI: This has been fixed here: ad91302f20908bf9f36d5b4d134f04283a3ef6a5

**Comment by thedaftbadger** [comment]
Fixed :+1: :smile:

**Comment by mrvautin** [comment]
Great. Let me know how you get on.
