### ISSUE TITLE
Encrypted details / access

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#10]
Sometimes I have to store sensitive or connection information in articles. How would be best to handle this? 
Password lock articles so you can only open them with a code?
Is the data within the KB file encrypted in any way?

I don't think a full blown user permissions structure would be the way forward as it would ruin the simplicity of openKB, but some way of locking certain articles may be handy.

**Comment by mrvautin** [comment]
This is an interesting one. Not sure how to handle it without making openKB overly complicated. The KB file data is stored in the clear if someone has access to the file system of the server.

Would a simple password prompt on the article be sufficient. Like you said, adding user permissions get complicated for something which would be used for a handful of articles.

**Comment by thedaftbadger** [comment]
I guess the easiest way in this case is to just add the ability to set a password for an article.

I don't thinking anything complex would be a good idea.

**Comment by mrvautin** [comment]
Added in: 722f88c848bba399c7b7b4fef503d075da30cc8c.
