### ISSUE TITLE
I have to generate new permalink every edit

### ISSUE THREAD

**Issue by peterbrinck** [mrvautin/openKB#100]
Hi

Just started using openKB today - And I really like it!

I just have one question:
Is it on purpose, that I have to generate a new permalink EVERY time I want to save an edit?
And if I try using a permalink that isn't in use, but HAVE been used before, I get the `Permalink already exists` error

**Comment by mrvautin** [comment]
I'm glad you like it!

No, the permalink should be retained on each save. I've just tested and it seems to be working fine in the latest version.

Is the permalink field being populated on the edit page?

**Comment by peterbrinck** [comment]
Yes, it is
The view count didn't work either

I fixed it by just removing openKB and download it again, and of course it worked
So my guess is that it/I had messed up the database some how

**Comment by Zelakto** [comment]
I'm also having this issue, I've upgraded from an earlier version as well. I guess I could go through the pain of reinstalling and making a database from scratch and re-add all my articles and hope that that solves the issue?

**Comment by peterbrinck** [comment]
That's what I did to resolve the issue
Removed everything and then just downloaded openKB from GitHub and then added all the articles back

And it's easy to get all the articles local since it's markdown and openKB has a built-in Export function under `Admin`

**Comment by mrvautin** [comment]
See #107.

**Comment by Zelakto** [comment]
I'm going to attempt to reopen this issue, since after importing all my articles, I still am getting this error. After some testing, it seems like the issue is with versioning, because if I turn versioning on and edit and article, it saves fine, but if I were to edit it again, it says an article already exists with that permalink. If I turn off versioning and edit another article twice, it works perfectly. I hope this helps!

**Comment by mrvautin** [comment]
Can your confirm if PR #121 fixes your issue @zelakto?

**Comment by Zelakto** [comment]
Sorry for the late response. Yes, PR #121 does indeed fix the issue. Thank you for all your help, @scaniatv and @mrvautin. You guys are simply the best. <3

**Comment by mrvautin** [comment]
👍
