### ISSUE TITLE
where  I  can  set  Featured articles ?

### ISSUE THREAD

**Issue by kongjc** [mrvautin/openKB#103]
hello,
 I want to know  where  I  can  set  Featured articles ?  thanks!

**Comment by mrvautin** [comment]
If you click the "Cog" icon in the editor a side menu appears where you can set the "Featured article" checkbox.

![image](https://cloud.githubusercontent.com/assets/299398/20002319/38c960e2-a2d0-11e6-85d2-f9893a87621b.png)

**Comment by kongjc** [comment]
ok，thank you！
