### ISSUE TITLE
Article Importer?

### ISSUE THREAD

**Issue by Zelakto** [mrvautin/openKB#107]
Since we can export articles, do you think it would be easy to implement an article importer? That way I could solve my issue in #100 much easier. I'd assume the way it'd work is I can upload a folder, or multiple `.md` files at once, and it would take the name of the file and make that the article name (and maybe have an option to make the permalink the article name as well). Thank you, keep up the awesome work!

**Comment by IllusionaryOne** [comment]
I have written an article importer that isn't very elegant, but so far, seems to work.  It takes liberties with regards to fields during the conversion process, but the MD files just do not have all the information that the DB file did.  I would like to enhance it to take command line parameters, as right now it requires three fields to be changed in the script.  If someone would find it of use:

https://github.com/IllusionaryOne/openKBImporter

**Comment by mrvautin** [comment]
👍

**Comment by mrvautin** [comment]
See here for a more built in solution: 9a194ff41faf2b3ceb600e1b46921d8f97021d2b

Let me know if it has any issues.
