### ISSUE TITLE
Possible to remove/change the kb in the URL?

### ISSUE THREAD

**Issue by peterbrinck** [mrvautin/openKB#108]
Hi!

When viewing an article/FAQ, there's a `/kb` in the URL (exmaple.com/kb/how-to-something)
Is there a way to change that to something else or remove it?

**Comment by mrvautin** [comment]
Could change it to something else quite easily but removing it would require some routing magic. Removing it would probably more trouble than it's worth.

To change it you can simply edit the `routes/index.js` file and change all the `/kb` routes to whatever you like.

**Comment by peterbrinck** [comment]
Oh okay, I'll just change it then 
Thanks :+1: :smile:

**Comment by samouuu** [comment]
Hi,

When u change all the /kb routes to whatever i like, a message display on the home : "Cannot read property 'find' of undefined" but i can navigate to login or suggest without problem
