### ISSUE TITLE
Mermaid Charts Info

### ISSUE THREAD

**Issue by BosnaZmaj** [mrvautin/openKB#111]
Do mermaid charts have to be installed separately or are they automatically included. I have them enabled in config but they are not rendering in article. I do have the div classes.

**Comment by mrvautin** [comment]
Mermaid charts are disabled by default because of the large file size.

You can enable through the `routes/config.js` file by setting:

`"enable_mermaid_charts": true`

**Comment by BosnaZmaj** [comment]
As per my comment I have them enabled but they still don't work.

**Comment by mrvautin** [comment]
Does the `mermaid.min.js` file show in the source?

The Mermaid charts don't seem to render in the editor but show when viewing the article.

**Comment by BosnaZmaj** [comment]
Yes the mermaid.min.js is found in the javascripts folder. Unfortunately they dont render when viewing the article. Below you can view the rendering of the article, and the source editor

![image](https://cloud.githubusercontent.com/assets/10079461/20670788/a30f6c0a-b548-11e6-998e-72ee4bf0f09a.png)


![image](https://cloud.githubusercontent.com/assets/10079461/20670756/734d2fca-b548-11e6-9afb-b23aeffca0bf.png)

**Comment by spatialsteve** [comment]
I am trying to overcome the same issue, and success @BosnaZmaj  ?
