### ISSUE TITLE
Inline_images are showing broken links

### ISSUE THREAD

**Issue by Phrendo** [mrvautin/openKB#113]
Hello.  
We just installed this kb a few days ago and as compared to Hazel and Raneto, we love it and decided to move forward with OpenKB.  My only issue so far is the inline images from within Chrome.

I can past an image, it shows a link and a file name, but then the image itself never fills out and the file is never placed in the inline folder.  Where should I look to help track this down?  

Thanks!

**Comment by mrvautin** [comment]
Thanks for your feedback.

Does the `inline_images` folder have write permissions?

**Comment by mrvautin** [comment]
This might be related to PR #112 which I just merged. Try pulling latest code and trying again.

**Comment by Phrendo** [comment]
It was a permissions issue.  I also ran this to get the latest.  Is this how I should be updating?

sudo git stash
sudo git pull
sudo git pop

This caused it to fail to start due to the missing 'speakingurl'
I installed that via npm and everything worked fine after that.  Is this the proper way to update?

**Comment by mrvautin** [comment]
Great you have it working. Yes, a `git pull` and a `npm install` should update fine.
