### ISSUE TITLE
locales

### ISSUE THREAD

**Issue by Amidel** [mrvautin/openKB#114]
Hi, how create locales (examle russian) and apply and use on this project?
thx

**Comment by mrvautin** [comment]
English is the native language. Copy the `en.js` file, rename to `ru.js` and translate into Russian. 

Thanks in advance for contributing!

**Comment by Amidel** [comment]
And it is made, but the Russian localization not apply.
I modify file: app.js  
`var i18n = new (require('i18n-2'))({
    locales: ['en', 'ru'],
    directory: path.join(__dirname, 'locales/')`
but not work locales

**Comment by mrvautin** [comment]
Adding an ability to change via config is on the TODO list. You can simply add `ru` first in your `app.js` file.
