### ISSUE TITLE
no search results for pages written in Chinese

### ISSUE THREAD

**Issue by choicky** [mrvautin/openKB#116]
Firstly, it's a very elegant wiki program. Thank you for your work.

I newly installed it and did a test.  I found openKB can only search English, can not search Chinese.

For example, if a search a Chinese key world, there is 0 hit.  Even if the Chinese key world is used as article tile or URL slug.

**Comment by unixben** [comment]
Multi-language support probably depends on [Suggestion: integrate language support within lunr.js](https://github.com/olivernn/lunr.js/issues/220)

**Comment by choicky** [comment]
@unixben 
@mrvautin 

This is an improved lunr which support Chinese search.   [https://github.com/codepiano/lunr.js](https://github.com/codepiano/lunr.js)

I replace `lunr.js` and `lunr.min.js` of openKB with those from the improved lunr and now openKB can search Chinese correctly.

After the repladcement, `npm install nodejieba` is required.
