### ISSUE TITLE
Can I put some articles into a directory or a category?

### ISSUE THREAD

**Issue by choicky** [mrvautin/openKB#117]
There are some articles that should be group into two directories or two categories.

Can I do this?

**Comment by unixben** [comment]
You can create keywords that represent categories.

Are you suggesting that articles be added to a category and displayed together, as is the paradigm in use on other wiki-like systems?

**Comment by mrvautin** [comment]
> You can create keywords that represent categories.

This is what I would do. The whole purpose of `openKB` is to be a searchable KB rather that one with nested categories. To get around that, you can use a common keyword which will link the articles together. You can then add Hyperlinks in your theme etc to: `/search/mycategory`
