### ISSUE TITLE
MultiLanguage search engine

### ISSUE THREAD

**Issue by Amidel** [mrvautin/openKB#118]
Hi, am found external repo: MihaiValentin/lunr-languages, 
but am not correctly connect this library to project.
how is it possible to connect it to the use of two language
Am create folder lib, and put into Lunr scripts, added to app.js code:
````
var lunr = require('lunr');
require('./lunr.stemmer.support.js')(lunr)
require('./lunr.ru.js')(lunr);
require('./lunr.multi.js')(lunr);

...
app.use(app_context + '/lunr', express.static(path.join(__dirname, 'lib/lunr')));
...

var lunr_index = lunr(function (){
    this.use(lunr.multiLanguage('en', 'ru'));
    this.field('kb_title', {boost: 10});
    this.field('kb_keywords');
````

But after start app, this broken.

Where I could make a mistake and how to fix it?

**Comment by unixben** [comment]
Refer to this workaround from @choicky https://github.com/mrvautin/openKB/issues/116#issuecomment-263066427

**Comment by Amidel** [comment]
Tnx, this workaround also applies to the Russian language
