### ISSUE TITLE
Create file JS language fr

### ISSUE THREAD

**Issue by samouuu** [mrvautin/openKB#128]
Hi,

I would like to clone en.js in order to add an other language.
When i try to clone, it's not display in settings.

Do you have an idea to display this ?

Bests regards

**Comment by unixben** [comment]
You likely need to restart openKB for the new language file to be included.

**Comment by mrvautin** [comment]
You will also need to add `fs` to the `locales` array the `app.js` file here:

```
// setup the translation
var i18n = new (require('i18n-2'))({
    locales: ['en', 'de', 'da', 'es', 'fr'],
    directory: path.join(__dirname, 'locales/'),
    defaultLocale: 'en',
    cookieName: 'locale'
});
```

**Comment by samouuu** [comment]
Thnaks :)
