### ISSUE TITLE
%5C link issue when running in IIS

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#130]
Latest version still has issues with inline images not displaying after successfully uploading correctly....
This is when running openKB under IIS with IISNode

![image](https://cloud.githubusercontent.com/assets/13657363/22685542/9c229c02-ed18-11e6-8834-0ed0383030fa.png)

`http://*****/kb/%5Cuploads%5Cinline_files%5Cimage-1486392639920.png`

**Comment by thedaftbadger** [comment]
Checked permissions for the public folder and they are correct. It seems to be the URL not generating properly.

**Comment by mrvautin** [comment]
Seems to be an issue with iisnode (I assume you are running that?): https://github.com/tjanczuk/iisnode/pull/486

Can you try grabbing this PR code and see if it resolves your issue?

**Comment by thedaftbadger** [comment]
Doest seem to work when adding the code to a web.config file for the app in IIS.

'''
<configuration>
	<system.webServer>
		<handlers>
			    <clear />
					<add name="iisnode" path="app.js" verb="*" modules="iisnode" />
					<add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
		</handlers>
		<rewrite>
			<rules>
				<rule name="sendToNode">
					<match url="/*" />
					<action type="Rewrite" url="app.js" />
				</rule>
				<rule name="static">
				<action type="Rewrite" url="www{REQUEST_URI}" />
				</rule>
				<rule name="serve-static" stopProcessing="true">
        <conditions logicalGrouping="MatchAny">
          <add input="{REQUEST_FILENAME}" matchType="IsFile" />
          <add input="{REQUEST_URI}" pattern="^/www/$" />
        </conditions>
      </rule>
      <rule name="node">
        <action type="Rewrite" url="app.js" />
      </rule>
			</rules>
		</rewrite>
	</system.webServer>
</configuration>
'''

**Comment by mrvautin** [comment]
Hmm. Just double checked and I don't think the PR is merged into the main branch yet and may require manual compilation.

**Comment by thedaftbadger** [comment]
@mrvautin Just done that ;)

**Comment by mrvautin** [comment]
To confirm: you grabbed that PR code and ran the build commands in the iisnode readme?

**Comment by thedaftbadger** [comment]
@mrvautin Yep still had the %5C issue in the file URL. I am giving up and switching back to nginx tomorrow 😋

**Comment by eugeneagafonov** [comment]
Just to leave the information for those who will search for solution:
- my PR fixes the issue, but it requires now creating a config file and explicitly defining the new behavior.
https://github.com/tjanczuk/iisnode/pull/486#issuecomment-222996458

- on Azure or other environments that are behind ARR (IIS app request routing) the url gets decoded before it reaches the app itsels, so for now it cannot be fixed

P.S. Do not run nginx on windows :)
