### ISSUE TITLE
Handling common document file types as attachments

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#137]
Just had a random thought..... we sometimes attach a PDF, Word or Excel (or other common file type) to an article. Currently we upload the file and then just provide a link to it. It might be an idea to have a way of attaching set documents that provide a common thumbnail etc.
What do you think? Sorry if this sounds completely random 😁

**Comment by mrvautin** [comment]
You could use Fontawesome (which is built-in) for file image/logo if you like. 

Eg adding a link like this: 
```
[<i class="fa fa-file-pdf-o fa-2x" aria-hidden="true"></i>
](http://domain.com/files/somepdfdocument.pdf)
```

Is that what you mean? Does that work?

**Comment by mrvautin** [comment]
@thedaftbadger any update on this issue?

**Comment by thedaftbadger** [comment]
@mrvautin Works well. I think in the long run we need to find a way of automatically handling files other than just ``inline_uploads`` for everything. Mixing .pdf with .jpg and other files is a little bit barmy 😁
