### ISSUE TITLE
Feature: Common colour settings

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#139]
Just a thought.... some way of setting common colours within the settings option.

* Header
* Header font
* Link  text colour
* Footer
* Footer font
* Search button
* Search button font

![image](https://cloud.githubusercontent.com/assets/13657363/23568137/2a0e1550-0051-11e7-913d-ecb64dd20343.png)

**Comment by mrvautin** [comment]
Good idea. Will try to get something like that in at some point.

**Comment by mrvautin** [comment]
Added in 63634f89eedbc77f8ad64ee4a3a53d78e6d92bf5.
