### ISSUE TITLE
Adding keywords buggy in Chrome

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#14]
Adding keywords is a little buggy on a few points...

* typing long words causes it to hide after a few characters

![keywords](https://cloud.githubusercontent.com/assets/13657363/9735829/7243cb3e-5635-11e5-84ea-b5a773e56ebb.png)
![keywords2](https://cloud.githubusercontent.com/assets/13657363/9735863/a126e8aa-5635-11e5-990b-584f84455a69.png)

* using backspace when in the keywords area doesn't delete keywords

**Comment by mrvautin** [comment]
Fixed in 9c29e6de077daf59933d7f98e16dc59fa6450b63.
