### ISSUE TITLE
lua language highlighting not working

### ISSUE THREAD

**Issue by jfemia** [mrvautin/openKB#141]
A fairly common extension to the markdown spec is to allow specification of language on code blocks, to help the syntax highlighter.

For example
```
```lua
-- some lua
```
(see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

I use this all the time and it would be nice to do this in openKB articles, since currently I can't find a way of getting correct Lua highlighting. Is there another way of specifying this on a code block in the md flavour used by openKB?

**Comment by jfemia** [comment]
After some more investigating, it looks like the support is present (using markdown-it), but Lua in particular isn't working in openKB.

The following snippet renders just fine in the markdown-it demo https://markdown-it.github.io/ (and also just fine right here on github):
``` lua
function foo()
  print("foo")
end
```

But this same code in openKB renders with no highlighting at all

**Comment by jfemia** [comment]
Looks like it's highlight.js - openKB appears to ship with the "pre-built" highlight.js with the 22 commonly used languages. Lua isn't one of these.

I downloaded my own highlight.js with more languages in, and dropped it in to `public/javascripts` to work around the issue

**Comment by mrvautin** [comment]
Great you got it working! Probably leave it at people adding their own languages if not supported by default highlight.js package.

**Comment by jfemia** [comment]
Hopefully if anyone else runs into this issue they find this issue / know to provide their own highlight.js :)
