### ISSUE TITLE
Having trouble with the static files, how can I get my Nginx config to work well with openKB?

### ISSUE THREAD

**Issue by vjk2005** [mrvautin/openKB#143]
If you view [https://dffrnt.com/wiki](url) right now you can see the static files are not coming through at all, some being 404 and others 503...
![screen shot 2017-03-16 at 7 46 55 pm](https://cloud.githubusercontent.com/assets/2087804/24002079/d1e2fa50-0a85-11e7-9a59-5039ab932e29.png)

My Nginx config...

    location /wiki {
		proxy_pass http://127.0.0.1:4444;
		proxy_redirect off;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-NginX-Proxy true;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	}

	location /wiki/static {
		alias /var/www/dffrnt.com/public_html/wiki/openKB/public/;
	}

And changes to my config.js...
`"app_context": "wiki”`

I feel the problem is Nginx, but if my assumption is wrong please point me in the right direction.

**Comment by mrvautin** [comment]
See here for a working Nginx config with an `app_context`: https://github.com/mrvautin/openKB/issues/142#issuecomment-286027399

Hope that helps.

**Comment by Wachiwi** [comment]
The requests for the static files don't have the path `/wiki/static/` as you can see in the console. you could adapt the config to handle css/js/images by using:

```
location ~* \.(?:js|css|jpg|jpeg|png) {
	alias /var/www/dffrnt.com/public_html/wiki/openKB/public/;
}
```
