### ISSUE TITLE
Markdown rendering bug

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#15]
Markdown with the new version is showing bullet and numbered lists correctly.
They look fine in preview but when live they are incorrect....

**In preview and edit**
![screenshot_090815_023400_pm](https://cloud.githubusercontent.com/assets/13657363/9736034/ce63c15c-5636-11e5-96c7-5522ae1c4dcc.jpg)

***

**When live**
![screenshot_090815_023549_pm](https://cloud.githubusercontent.com/assets/13657363/9736057/ea097be0-5636-11e5-9c3e-9a2902bc1622.jpg)

Bullet points seem to have been converted to a numbered list!?

**Comment by thedaftbadger** [comment]
I can confirm that the last commit was not the cause of this error.
This is the same for commits `4c666b1` and `5c03d03`

**Comment by mrvautin** [comment]
Fixed in 1a12b3a8fc9778d2c83baf83380b9236dbc50542.
