### ISSUE TITLE
The site adds translations to files

### ISSUE THREAD

**Issue by plehanov** [mrvautin/openKB#152]
When saving the configuration file, more lines of data are stored in the translations. With a deploy, I have to do a hard reset in order to correctly roll changes.

What is the reason for this?

In en.js are added such lines:

```
   "Setup": "Setup",
   "Email address": "Email address",
   "Confirm password": "Confirm password",
   "Complete setup": "Complete setup"
```

**Comment by mrvautin** [comment]
Translations are added automatically to the english file when unrecognised phrases are found. It's possible that those pages haven't been visited before (by me) and thus I've not committed those phrases to the english locale.

**Comment by plehanov** [comment]
I understood. Add if necessary. So it will be clear what else requires translation))
