### ISSUE TITLE
custom URL size error

### ISSUE THREAD

**Issue by vikaskedia** [mrvautin/openKB#163]
![image](https://cloud.githubusercontent.com/assets/6703876/24617690/87007568-1849-11e7-9b3e-5d7819970dbf.png)

When using embedded DB my custom URL works fine:
![image](https://cloud.githubusercontent.com/assets/6703876/24617713/9813d106-1849-11e7-841d-fd72434e1cdc.png)

But, when using Mongo DB:
I need to shorten the above custom URL by at least 1 character.

**Comment by unixben** [comment]
Related to [MongoDB's ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) size being 12 bytes long.

**Comment by mrvautin** [comment]
Yeah a weird bug there. Haven't had the chance to look at it yet. The MongoDB port is relatively new code.

**Comment by mrvautin** [comment]
I don't get the error message when using that permalink in your example and using Mongodb.

Can you give me the steps to reproduce the error? Are you clicking the "Save" button or the "Validate" button or something else? I don't get any errors when trying to save, update or view the KB.
