### ISSUE TITLE
randomly search hangs and makes the browser tab non responsive

### ISSUE THREAD

**Issue by vikaskedia** [mrvautin/openKB#164]
This seems like a difficult bug to track down so I made a video.

Here is the link:
https://www.youtube.com/watch?v=XKlwAdyrL0Q

The problem gets solved if I restart the docker container running openKB.

**Comment by mrvautin** [comment]
Are you able to bring up the browser inspector and test again to see if there are any errors when fetching the live search results?

**Comment by mrvautin** [comment]
Tracking in #171.
