### ISSUE TITLE
Guide to Deploy to DO?

### ISSUE THREAD

**Issue by wondersoftheworld** [mrvautin/openKB#167]
hello,
i like the simplicity of the localhost install. 
any simple guide to deploy openkb to digitalocean from my localhost install?
it was mentioned in the docs that pm2 is preferred.
which file do i run/start pm2 process on?

thanks.

**Comment by mrvautin** [comment]
You can run `openKB` on DO or any other server using PM2 by:
```
pm2 start app.js -n 'name_for_process'
```

**Comment by wondersoftheworld** [comment]
awesome! thanks.
