### ISSUE TITLE
Voting does not appear on Twitter theme

### ISSUE THREAD

**Issue by wondersoftheworld** [mrvautin/openKB#168]
hello,
although i have enabled voting from settings, when using the twitter theme, voting does not show on articles. when i switch the theme to the default, then voting shows.
how can i make voting show on twitter theme?

thanks.

**Comment by warrenmcquinn** [comment]
Thanks for posting about this issue @wondersoftheworld  -- I found the same problem.

Here's the issue:

The Twitter KB layout is missing a hidden input that captures the document ID, which the backend needs to know which article is receiving a vote.

Here's where the backend is supposed to be receiving `$('#doc_id').val()`:
https://github.com/mrvautin/openKB/blob/master/public/javascripts/openKB.js#L279

The hidden input in question:

`<input type="hidden" id="doc_id" value={{result._id}}>`

Here's where it should go:
https://github.com/mrvautin/openKB/blob/master/public/themes/twitter/views/kb.hbs#L115

The hidden input is found in another theme's KB layout:
https://github.com/mrvautin/openKB/blob/master/public/themes/darkly/views/kb.hbs#L110
