### ISSUE TITLE
New markdown

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#17]
The new markdown being used seems to have lost a lot of nice features...

* Bullet lists seem to render incorrectly
* tables seem basic now and don't have hover over row highlighting

I'm not sure what else has changed, but from what I can see it doesnt seem as clean or asthetically pleasing compared to the last release.

Not sure if this was caused by the last release or the change of MD?

**Comment by thedaftbadger** [comment]
I can confirm that the last release / commit has caused the table style and markdown to change

**Comment by mrvautin** [comment]
Cannot replicate. Tables working with hovering rows and lists working as designed. Using markdown-it for all markdown rendering so am at the mercy of that library.
