### ISSUE TITLE
Markdown tables issues

### ISSUE THREAD

**Issue by thenaturalist** [mrvautin/openKB#170]
Hi, 

first of all let me thank you very much for building openKB, it's a really great free product. 
I was a bit puzzled today when playing around with the editor to find out that tables are rendered without any borders. Column headers are bold and lines are highlighted upon hovering, but all structural visual elements of the table are missing, greatly decreasing the overview. 

I am using standard markdown and when using the same code here on Github, the results are displayed as expected: 

| Column 1 | Column 2 | Column 3 |
| -------- | -------- | -------- |
| John     | Doe      | Male     |
| Mary     | Smith    | Female   |

Also note how the table here in the ticket only expands as far as the column header contents. In the article view, tables and code blocks are spread over the entire width of the article `div` element.

Does this have to do with Markdown-it, or is this an individual styling option I can adapt somewhere in the code or is this a bug?

**Comment by mrvautin** [comment]
openKB uses bootstrap and thus tables are "responsive" and 100% width by default.

You can however override that with CSS if you wish or using some HTML in your Markdown. Eg: Wrapping a table in:

``` html
<div class="col-md-6">
<!-- table markdown code here -->
</div>
```

Will make the table 6 grid colums wide or 50% of parent div.

**Comment by mrvautin** [comment]
You can also change the class added to each table by editing: /public/javascripts/openKB.js

When displaying you can edit line 19 to:

``` javascript
$(this).addClass('table table-hover table-bordered');
```

For the live editor preview you can edit line 257 to:

``` javascript
fixed_html = fixed_html.replace(/<table/g, "<table class='table table-hover table-bordered' ");
```

**Comment by thenaturalist** [comment]
Perfect, thanks!
