### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by mikespence** [mrvautin/openKB#173]
Hi - thanks for this, it's great!

One quick question, is there a way to have user publishing permissions? We'd like general users to submit articles that must be reviewed first.

Would there also be a way of having a user group for creating and publishing articles only, not all the site settings?

Thanks,

Mike

**Comment by mrvautin** [comment]
This functionality is not currently in place however the "Suggest" feature could work for you. After switching the `suggest` setting to `true` you can direct "General users" to `mykb.com/suggest` to submit articles. 

After articles are Suggested they are in `Draft` state and require manual switching to `Published`.

Eg: [https://openkb.markmoffat.com/suggest](https://openkb.markmoffat.com/suggest)
