### ISSUE TITLE
Filter keywords contains '/' need to escape with encodeURIComponent()

### ISSUE THREAD

**Issue by gsw945** [mrvautin/openKB#177]
At **Admin article management** ![](https://raw.githubusercontent.com/mrvautin/mrvautin.github.io/master/images/openkb/openkb_articlefiltering.png)
If filter keywords contains '/', the **404** error will appear. In my own case:
the keywords i inputted was `A/VR-API-`, and the url of chrome will changed to `http://localhost:4444/articles/A/VR-API-` with the 404 error, I konw that the raw `/` will lead to url path error. then I use the development-tool's console
```javascript
> encodeURIComponent('/')
<. "%2F"
```
,and modified the url to `http://localhost:4444/articles/A%2FVR-API-` manually.
all was OK, my article list appeared.
So, please escape the characters of the filter keywords to avoid url path error appearing.

**Comment by mrvautin** [comment]
You are welcome to submit a PR and assist with the project..

**Comment by gsw945** [comment]
@mrvautin I created a pull request [PR-178](https://github.com/mrvautin/openKB/pull/178) to fix it.
