### ISSUE TITLE
Vulnerability: Suggest Post Feature

### ISSUE THREAD

**Issue by jagracey** [mrvautin/openKB#181]
I would normally keep this issue private to the repo maintainer until resolved, but in this case it looks like there is no active maintainer.

Markdown used by OpenKB allows for script tags. This is a great feature for admins. The problem is that user submitted "suggested posts" could contain malicious JS. Most knowledge bases are hosted under a subdomain, in general leading to CSRF token exposure and full exposure if the main auth cookie isn't "HTTPOnly" protected, which many SaaS tech companies do not do this.
.
The Markdown preview on the editor page should be Iframe sandboxed to allow JS to be executed, but effectively have near zero impact*. I for one will simply turn off the Suggest Post feature.

*postMessage() is can be utilised as an attack vector, but most websites listening to message events should already be aware and whitelisting by origin (Again, many don't).

**Comment by jagracey** [comment]
@mrvautin

**Comment by jagracey** [comment]
The Topics/Kewords also inject unsanitised user generated HTML.

**Comment by mrvautin** [comment]
Thanks for reporting. Here is my first attempt at fixing: 90fd8350d9b8f879b0690319f24dbc4b0dc45d2e.
