### ISSUE TITLE
Only some articles for non-logged in users

### ISSUE THREAD

**Issue by tyelford** [mrvautin/openKB#183]
Is there a way that would allow logged in users to see all articles and also allow logged in users to 'push' certain articles for non-logged in users to see?

Use case: The IT department creates lots of articles on how to do IT things, but also creates How-to articles for staff to read.  The IT department can choose which articles the staff (non-logged in users) can see.

**Comment by mrvautin** [comment]
We already have this on [ezyFAQ](https://www.ezyfaq.com).

I will look at implementing on `openKB` also.

**Comment by mrvautin** [comment]
Added this feature to a degree in 7d97adb027be45b988827098f771b107aa16b5dd. Articles can be set to private which requires a valid login to be able to view.
