### ISSUE TITLE
Ever considered external storage adapter?

### ISSUE THREAD

**Issue by toddheslin** [mrvautin/openKB#184]
I'm loving this project - thanks so much @mrvautin!

I've deployed to Heroku and it seems that one of the problems is that images are saved to the server. Heroku would simply wipe these on a rebuild if we wanted to make changes to the theme. Have you considered an Amazon S3 adapter for storing and retrieving images?

**Comment by mrvautin** [comment]
Yes I see your point regarding Heroku. I've developed it already as ezyFAQ (eg: hosted openKB) has S3 built in.

If someone submits a PR to enable S3 as a optional setting I would definitely merge it.

**Comment by toddheslin** [comment]
Great call @mrvautin I've moved to Digital Ocean to keep it simple now, but this seems like a great project to contribute to.

**Comment by SalahAdDin** [comment]
👍
