### ISSUE TITLE
Changing email

### ISSUE THREAD

**Issue by toddheslin** [mrvautin/openKB#186]
It would seem that it's not possible to change the email for a user through the admin interface.

Which option would be the best?
- Directly edit mongo
- Using the REST API (not sure if there was a method to update the email)

Are there any other considerations why changing the email is not allowed?

**Comment by SalahAdDin** [comment]
👍

**Comment by mrvautin** [comment]
There is no REST API to change the email address for a given accounts nor is there a reason for `not` implementing it.

Considerations would include updating of "last updated by" and "published by" for all FAQ docs in the database with the new email address/name.

It could be done relatively easy if someone has the time to submit a PR. Unfortunately I don't have the time right now to add that functionality.

**Comment by toddheslin** [comment]
Thanks Mark. I've just taken the simple option of creating a new admin user and logging in with this instead. Simple 🥇 

All good on the time for the PR. I've forked the repo so plan to add these things as I find them.
