### ISSUE TITLE
Adding keywords bug

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#19]
Some articles wont allow keywords to be entered.

Running a clean copy of the latest version. Browser = chrome (latest build)

**Comment by thedaftbadger** [comment]
Articles already with Keywords added allow you to add more but existing articles without or new articles don't allow you to add any keywords.

**Comment by thedaftbadger** [comment]
@mrvautin Just created a new instance of the latest build and entering keywords is not possible. It's as if the field to type in is blocked.

**Comment by thedaftbadger** [comment]
@mrvautin New articles in a clean environment and the upgraded ones are ok. It seems that if an article didn't have keywords added in the previous build it is now not possible to enter any.

Old articles with existing keywords work ok and so do new articles.

Could it be an issue with the `kb.db` ?

**Comment by thedaftbadger** [comment]
Opening an article with some keywords but when clicking edit the keywords are not shown / disappear and you are unable to add any.

**Comment by mrvautin** [comment]
Fixed in 9c29e6de077daf59933d7f98e16dc59fa6450b63.
