### ISSUE TITLE
Problem starting openKB on raspberry pi

### ISSUE THREAD

**Issue by ginspet** [mrvautin/openKB#191]
Dear Mark,

I'm experimenting with openKB and like it a lot. Great job of yours.
I now also tried to install the package on a raspberry for testing. Installing working fine, but starting throws an error.
Is this an error in the package? Anything I can do to get this running?
Thanks a lot for your answer in advance,

Peter

output:
> openkb@1.0.22 start /opt/openKB
> node app.js

/opt/openKB/routes/index.js:1473
ddir(path.join(__dirname, '..', 'public', 'temp', 'import'), (err, files) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/openKB/app.js:22:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! openkb@1.0.22 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the openkb@1.0.22 start script.
npm ERR! This is most likely a problem with the openkb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls openkb
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /opt/openKB
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/openKB/npm-debug.log
npm ERR! not ok code 0

npm-debubg.log shows:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart openkb@1.0.22
6 info start openkb@1.0.22
7 verbose unsafe-perm in lifecycle true
8 info openkb@1.0.22 Failed to exec start script
9 error openkb@1.0.22 start: `node app.js`
9 error Exit status 8
10 error Failed at the openkb@1.0.22 start script.
10 error This is most likely a problem with the openkb package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node app.js
10 error You can get their info via:
10 error     npm owner ls openkb
10 error There is likely additional logging output above.
11 error System Linux 4.9.35-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /opt/openKB
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by mrvautin** [comment]
Thanks. You need to update your Node.js version.
