### ISSUE TITLE
Image ok in preview but not live

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#2]
Image showing perfectly when creating an article within the preview window...
![Article edit and preview](https://cloud.githubusercontent.com/assets/13657363/9625275/c27b2edc-514c-11e5-8953-452c9323305e.jpg)

But when the article is published the image is not valid...
![live article error](https://cloud.githubusercontent.com/assets/13657363/9625298/f23cf57e-514c-11e5-9de3-3abce36bfd7a.jpg)

The image URL is the same if I inspect the page and manually browsing to the image works ok.

**Comment by mrvautin** [comment]
What about an image hosted on a different domain? Eg: does this work? http://cdn0.dailydot.com/uploaded/images/original/2014/5/26/google-logo-before-after.gif

Are you able to send the HTML source of the "Live" page/article?

**Comment by thedaftbadger** [comment]
That image works ok in preview....

![google image](https://cloud.githubusercontent.com/assets/13657363/9626203/ae7a21a2-5153-11e5-805e-56b807637150.jpg)

And it also displays ok when the article is live...

I don't see how it can be a permissions issue if I can manually browse to the image using the direct URL and it displays ok in the preview?

![screenshot_090215_092130_am](https://cloud.githubusercontent.com/assets/13657363/9626239/ffff7a0e-5153-11e5-857b-9d860a568151.jpg)

I have another NodeJs application running with images in the Public folder which work perfectly.

**Comment by thedaftbadger** [comment]
I have just noticed this in the server CLI when the page loads....
![image](https://cloud.githubusercontent.com/assets/13657363/9626570/748e759e-5156-11e5-8896-100ae4d2f2ea.png)

**Comment by mrvautin** [comment]
Hmm. Out of interest. Does it work when you have your images directly in the "images" folder and not beneath the "outlook" folder?

**Comment by thedaftbadger** [comment]
I completely reinstalled NodeJs and openKB and now it seems to work fine. Even with sub-folders within the `images` folder.

Just out of interest are you actively developing openKB? I have a few features to request that would improve it a little bit :smile: 

We tried using Raneto markdown KB system but I much prefer the simplicity of this one.

**Comment by mrvautin** [comment]
Yes definitely. I use an install of it every day. It's deliberately not bloated with features but I'm open to new ideas.

Just raise a new issue with your ideas.
