### ISSUE TITLE
Author details missing

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#20]
`Author` blank at the bottom of aticles.
Suggest maybe using First and Last name of user account (would require new fields).

![screenshot_092215_082321_am](https://cloud.githubusercontent.com/assets/13657363/10012812/4c6d9150-6103-11e5-8c0a-80a747ac66bd.jpg)

**Comment by thedaftbadger** [comment]
This was a local issue with a user account but still suggest changing email to users name for clarity.

**Comment by mrvautin** [comment]
Author details will be blank for existing articles before the last update. I could put something in place whereby "re-saving" existing articles without an author will set the current editing user as the author. Would that work?

**Comment by mrvautin** [comment]
Fixed in ded94f668df995fd97d185b74e49cc2d7cafb94a.
