### ISSUE TITLE
case sensitivity with username

### ISSUE THREAD

**Issue by JDCain** [mrvautin/openKB#205]
due to creating some account with copy and paste I noticed that when logging in to the app the username/email has to be in the same case as it was created in order for the database look up db.users.findOne({user_email: req.body.email}, etc to work. 

Some older posts I found online mentioned using regex to fix it but being new to nodejs / express I was not sure if there was a better way.

**Comment by SalahAdDin** [comment]
@JDCain did you stop to work with this?
