### ISSUE TITLE
Unexpected token >at root/openKB/routes/index.js:1473

### ISSUE THREAD

**Issue by putrapdp** [mrvautin/openKB#212]
Please help with this error : 
Im using Ubuntu 14.04

> root@ubuntu:~/openKB# npm start
> 
> > openkb@1.0.22 start /root/openKB
> > node app.js
> 
> 
> /root/openKB/routes/index.js:1473
> ddir(path.join(__dirname, '..', 'public', 'temp', 'import'), (err, files) => {
>                                                                            ^
> SyntaxError: Unexpected token >
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/root/openKB/app.js:22:13)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
> npm ERR! weird error 8
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! not ok code 0
> 

thank you

**Comment by mrvautin** [comment]
You probably need to upgrade your Node.JS version. See readme for minimum version.

**Comment by putrapdp** [comment]
thanks sir, let me try with newer node.js
