### ISSUE TITLE
Tables and bootstrap class is not working

### ISSUE THREAD

**Issue by bkovacev** [mrvautin/openKB#217]
Bootstrap classes
![image](https://user-images.githubusercontent.com/5438972/29785314-66faf2e6-8c27-11e7-9d8b-c15fa65171d7.png)

and table
![image](https://user-images.githubusercontent.com/5438972/29785331-77aa21d4-8c27-11e7-995f-a44957b5c092.png)

How do I even approach debugging this?

**Comment by mrvautin** [comment]
This is likely just the live preview and not reflected once the article is saved.
