### ISSUE TITLE
Feature: Drag to upload

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#22]
Maybe integrate the drag to upload feature? The same way GitHub works when adding images. 

This would make creating articles very fast.

Drag image onto article composing section.... image auto uploads and correct markdown is written automatically.

What do you think?

Images uploaded in this way would need a unique number / code assigning to them, maybe also in a sub-folder within 'uploads'

**Comment by thedaftbadger** [comment]
This is the closest I can find....

https://github.com/Rovak/InlineAttachment

**Comment by thedaftbadger** [comment]
Would that work?

**Comment by mrvautin** [comment]
Looks pretty decent. Would have to figure out how to manage files unused files. I assume it could get out of hand with a change of mind on a file, updated file, wrong file attached etc. Maybe could have a clean up task which loops the files and checks whether the URL to that file is in a KB's article and deletes any non used files. I assume GitHub has a similar task/job.

Thoughts?

**Comment by thedaftbadger** [comment]
Yeh the file management is an issue with this one. Like you said I would guess GitHub uses a cleanup script that can be run manually when needed. 
Not sure something needs to be automatic, or at least it wouldn't for our production environment.

As you mentioned it basically needs to check if the file is in use / referenced in a published or draft KB article. If not it could be deleted. Ideally all of these "auto uploaded" files would have to go into their own folder to keep things neat.

**Comment by mrvautin** [comment]
@thedaftbadger

Functionality added in: ca73b256a794c07cb21a1da643e347e7ec2a432d. Let me know how you go with it.

**Comment by thedaftbadger** [comment]
Function works great :)
