### ISSUE TITLE
Is there a way to get Sidebar for Navigation ?

### ISSUE THREAD

**Issue by ExtremeGTX** [mrvautin/openKB#220]
Hi
Is there a way to get a sidebar for navigation like Wiki sites, so it will make it easier for visitors to explore the available articles/topics ?

**Comment by priedthirdeye** [comment]
I was looking for the same thing. Perhaps a "tag cloud" could help accomplish the goal too.

**Comment by mrvautin** [comment]
You would need to create a theme and add your sidebar.
