### ISSUE TITLE
Interested in Asciidoc support?

### ISSUE THREAD

**Issue by tkfu** [mrvautin/openKB#221]
Hi,

I liked the looks of openKB, but I'm not crazy about Markdown. So I spent an hour or so on a [very hackish change allowing the use of Asciidoc](https://github.com/tkfu/openKB-asciidoc/tree/feat/use-asciidoctor) instead. It works great, suits my needs for now, and was quite easy, but it's definitely not clean enough for a PR (it just removes markdown support instead of adding a config option/toggle for asciidoc).

If I were to clean it up and add a configuration option for selecting markdown vs. asciidoc, would you consider merging it in? Or should I leave this as a personal hack?

**Comment by mrvautin** [comment]
Pretty happy with Markdown as it’s really popular now. Probably keep your changes as a personal fork. Good work though!
