### ISSUE TITLE
When I Drag and Drop the file it is uploaded but the article stays in ![Uploading file...]()

### ISSUE THREAD

**Issue by rzunigacr** [mrvautin/openKB#240]
When I Drag and Drop the file it is uploaded but the article stays in ![Uploading file...]() I google this everywhere and everywhere it says this was fixed can someone help me get this to work?

PIC files are uploaded to the article ok and TXT files too but any PDF or ZIP file has this wear behavior

![image](https://user-images.githubusercontent.com/34085305/34650654-4aa0f21a-f38a-11e7-9e7b-303c791fd87c.png)

**Comment by mrvautin** [comment]
Its probably a permissions problem. Check your console and check if the uploads folder is writable by the process running the application.
