### ISSUE TITLE
Feature: Lock icon for identification

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#25]
Lock icon beside articles for both admin and user for easy identification of passworded articles.

Rough example...

![lock symbol_top](https://cloud.githubusercontent.com/assets/13657363/10040539/83a756fc-61d4-11e5-817b-cafbe9dd7cc2.png)
![23-09-2015 09-20-39](https://cloud.githubusercontent.com/assets/13657363/10040538/83a6f888-61d4-11e5-958f-59bc332521c4.png)

**Comment by mrvautin** [comment]
Added: e376d5919ff9b2c4020cb85211408c45242db028
