### ISSUE TITLE
newbie question - heroku free - application reset after 30 minutes...?

### ISSUE THREAD

**Issue by toffitomek** [mrvautin/openKB#257]
I want to test openKB under Heroku free tier but it seems to reset to Setup after a while.
- is this normal? 
- is this related to Heroku Free tier sleeping? 
- using app like uptimerobot.com will keep it ON?

thanks in advance

**Comment by mrvautin** [comment]
It’s likely related to Heroku sleeping. I believe you can’t setup a poll to keep it awake but I’m not Heroku authority. 

If I were you, I would get a cheap DigitalOcean droplet and host here.
