### ISSUE TITLE
Feature: Video embed

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#26]
Sometimes we have the need to store help / guide videos in articles, especially on complex processes.

Maybe look at integrating some sort of video embedding from internal. We would not host any of these videos publicly (Youtube etc) but could store them as MP4 in the `uploads` folder.

**Comment by mrvautin** [comment]
I know this is not Markdown but you can embed Videos below. Unfortunately there is not an agreed Markdown syntax for videos in the CommonMark syntax yet:

```
<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="http://127.0.0.1:4444/uploads/Video.mp4"></iframe>
</div>
```

This can also be used for YouTube

```
<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/watch?v=dQw4w9WgXcQ"></iframe>
</div>
```
