### ISSUE TITLE
Feauture: Diagrams

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#27]
Integration of diagrams / flow charts via markdown.

Maybe with https://github.com/knsv/mermaid

**Comment by mrvautin** [comment]
Added in e14160bffc04f071e04b970c432d161e31f12f59.

Can add charts by simply adding code like this to an article - detailed doc: https://github.com/knsv/mermaid

```
<div class="mermaid">
graph LR;
    A[Hard edge]-->B(Round edge);
    B-->C{Decision};
    C-->D[Result one];
    C-->E[Result two];
</div>
```

The default styling of Mermaid is terrible. Added own theme but may need work. Please raise an issue if any colour/style fails are seen.
