### ISSUE TITLE
Bug: Mermaid diagrams

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#28]
Using the following markdown should render a simple A > B chart but nothing renders...

````
graph LR
    id1
````

Have tried other mermaid markdown but nothing renders.

**Comment by thedaftbadger** [comment]
Also tested following markdown...

````
graph LR
    A[Square Rect] -- Link text --> B((Circle))
    A --> C(Round Rect)
    B --> D{Rhombus}
    C --> D
````

**Comment by mrvautin** [comment]
Are you wrapping the chart in the following div?

```
<div class="mermaid"></div>
```

Eg:
![image](https://cloud.githubusercontent.com/assets/299398/10155529/9dc30f64-66b5-11e5-9c02-9ab23f6fb9cd.png)
