### ISSUE TITLE
Feaure: Caution, Warn, Tip, Info Box

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#29]
I know it isn't in the standard Markdown but it would be good to add Caution, Warn, Tip or Info Boxes into the options.

Just expands the capability of articles within the system.

Something like this.... https://wiki.nci.nih.gov/display/WikiTrainFAQsTips/Creating+a+caution,+warning,+tip+or+info+box

**Comment by mrvautin** [comment]
This has been added in 0eeac216701663b98170e3050f6f11cf870ddec0

More info can be seen in some doco I've written up here under "Markdown classes": http://openkb.mrvautin.com/kb/WpqMvGFLW2a9kBsO
