### ISSUE TITLE
Improved search

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#3]
I really really like openKB and I think it is the best Markdown knowledge base available at the moment but one feature that lets it down is the search. It just doesn't seem good enough, especially when lots of articles are in the Knowledge base.

For example....

I have an article called **DECT 400 Status Icons** which also has the tags `dect` `400` `symbol` `icon` `status`
If I search for _DECT Icons_ nothing is returned.

[Raneto](https://github.com/gilbitron/Raneto) (another markdown KB) has a brilliant search but I think it works off an articles description. Could the search in openKB work the same as Raneto?

**Comment by mrvautin** [comment]
I agree the search is a bit lacking. I can reproduce the issue and will look into it further.

**Comment by thedaftbadger** [comment]
:+1: :sunglasses:

**Comment by mrvautin** [comment]
Fixed (hopefully) in latest commit.

**Comment by mrvautin** [comment]
Closing this issue. Will reopen if not fixed, requires more work or introduced bugs.

**Comment by thedaftbadger** [comment]
Works brilliantly :)
