### ISSUE TITLE
Bug: Lock Icon

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#30]
Lock icon issued in commit `e376d5919ff9b2c4020cb85211408c45242db028` not working in the latest release.

https://github.com/mrvautin/openKB/commit/e376d5919ff9b2c4020cb85211408c45242db028

Tested on both Chrome and IE

**Comment by mrvautin** [comment]
Odd. Can you confirm if the "font-awesome.min.css" file is present in the /public/stylesheets/ folder? May need to also confirm the stylesheet is referenced in the "/views/layouts/layout.hbs" file.
