### ISSUE TITLE
how to add tags for HLS player ? from momovi ?

### ISSUE THREAD

**Issue by omgbox** [mrvautin/openKB#33]
dude, how to add tags for HLS player ?

like 

hls-video://example.m3u8

please advice. i love openKB

https://momovi.com/opensource/momovi-video-hls

**Comment by mrvautin** [comment]
I'm not familiar with the format. Have you tried simply pasting in the HTML code in the editor? There is no "markdowny" way to embed it. You might need to get creative. Eg: [openKB - embed video](http://openkb.mrvautin.com/kb/TBOyVtJjEP5FVjbX)

Are you using openKB on a public website? If so, I'd be interested in seeing a link.

**Comment by mrvautin** [comment]
Also see this issue: https://github.com/mrvautin/openKB/issues/26

**Comment by mrvautin** [comment]
Closing as solved. Happy to reopen if more help needed.
