### ISSUE TITLE
KB Article URL

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#34]
KB articles URL's are usually quite complex / random e.g. http://openkb.com/kb/hM4CWiUADw0ovIXB

Is there any way of making this more numerical so that it is easy for searching and giving out to people. For example ask a person to search for KB article 45678 and it shows the correct article. The URL for said article would be http://openkb.com/kb/45678

I hope that makes sense?

**Comment by mrvautin** [comment]
I've added this feature and done a pretty extensive rewrite of some code, redesign and cleanup. 

I tried to do as a separate release but my Git application totally messed things up so its in this commit: https://github.com/mrvautin/openKB/commit/ccd434fe68141ebb86834eaf299dd1533a547e1b
