### ISSUE TITLE
404 server side

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#36]
Showing 404 for the following URLs server side....

`GET /stylesheets/bootstrap-tokenfield.css 404`
`GET /javascripts/markdown-it-classy.js 404`
`GET /javascripts/openKB.js 404`

**Comment by mrvautin** [comment]
Do those files exist in /public/stylesheets/ and /public/javascripts/? They exist in the repo.

Maybe you could do another 'git clone' and try again. It seem to be missing files which is causing issues.

**Comment by thedaftbadger** [comment]
All the files are there and I can see them

**Comment by mrvautin** [comment]
Did a clean install resolve the 404 errors?

**Comment by thedaftbadger** [comment]
Yep that fixed it
