### ISSUE TITLE
Creating new article bug

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#38]
- Create new article
- Set Title
- Set Status to published
- Fill out content
- assign tags
- Save / create the article

Article is created but....

- status is reverted back to draft
- tags are removed

Re adding the tags and setting the status to publish at this point now works.

**Comment by mrvautin** [comment]
I thought I noticed this testing earlier but forgot to go back and test. I will have a look.

**Comment by thedaftbadger** [comment]
I think this bug has been around for a while but I forgot to mention it :)



On Feb 05, 2016, at 09:46 AM, Mark Moffat <notifications@github.com> wrote:

I thought I noticed this testing earlier but forgot to go back and test. I will have a look.
