### ISSUE TITLE
404 Bad Gateway

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#39]
Seeing the following errors server side fot the latest build...

`GET /error/HTTP_BAD_GATEWAY.html.var 404`

Still trying to pinpoint when this happens. Does the system rely on any externally hosted content / cdn?

**Comment by mrvautin** [comment]
It does have cdn content. Both are:

https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/flatly/bootstrap.min.css


https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.min.js

They could be bundled with the app.

**Comment by thedaftbadger** [comment]
CDN side is nice but then again sometimes I can see a need for people to have it in a closed / locked environment. What do you think?


On Feb 05, 2016, at 09:45 AM, Mark Moffat <notifications@github.com> wrote:

It does have cdn content. Both are:
https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/flatly/bootstrap.min.css
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.min.js
They could be bundled with the app.

**Comment by mrvautin** [comment]
CDN's are at their best on public facing websites where users are in multiple locations. 

As its only two, I will add them to the project I think.

**Comment by thedaftbadger** [comment]
Good call. It's not massive if it was bundled.



On Feb 05, 2016, at 09:54 AM, Mark Moffat <notifications@github.com> wrote:

CDN's are at their best on public facing websites where users are in multiple locations.
As its only two, I will add them to the project I think.
