### ISSUE TITLE
Question: Current URL

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#40]
For the article information section where is the Current URL defined?

My instance always shows `http://localhost` but we have another DNS address assigned to it. Can this be set anywhere in the config?

**Comment by mrvautin** [comment]
It will always listen on localhost although if you have multiple interfaces you can have it listen on other Interfaces by editing the 'app.js' file. 

If you are wanting to point a DNS to openKB you will likely have to setup Nginx, Apache or IIS (I assume IIS can do this) to point to http://localhost:4444.

**Comment by thedaftbadger** [comment]
Running Apache for this as it is a little easier than IIS :)

**Comment by mrvautin** [comment]
Everything is easier than IIS ;)

**Comment by thedaftbadger** [comment]
Ha ha.

For the KB Article Permalink details in the footer it defines the permalink using `{{current_url}}`
Is this something that can be set manually? Where is the `{{current_url}}` defined? Without manually removing / changing this all the permalink information in the KB article footer is always `http://localhost`

**Comment by thedaftbadger** [comment]
`<strong>Permalink:</strong> <a href="{{current_url}}/kb/{{result.kb_permalink}}" target="_blank">{{current_url}}/kb/{{result.kb_permalink}}</a>`

**Comment by mrvautin** [comment]
{{current_url}} gets the current URL being used in the request. Eg: If you are using http://localhost:4444 then this will be the {current_url}}. If you have Apache or Nginx setup and serving the page via DNS then http://kb.example.com (for example) will be show in the {{current_url}} variable.

**Comment by thedaftbadger** [comment]
That's strange. I server both instances of openKB via Apache and both have always displayed http://localhost as the current URL despite what Apache Virtual Hosts has configured.

**Comment by mrvautin** [comment]
It's likely an issue with the Apache configuration not passing through the `Host` header correctly.

In Nginx (which I'm familiar with) you set it like so:

    server {
        listen 80;
        server_name example.com;
        location / {
            proxy_set_header Host $host;
            proxy_pass http://localhost:4444;
        }
    }

**Comment by mrvautin** [comment]
How did you go with this one? Can I close it off?

**Comment by thedaftbadger** [comment]
Still investigating this one. Hopefully an update soon.

**Comment by mrvautin** [comment]
Closing due to not hearing back. Can re-open.
