### ISSUE TITLE
Bug: Show author email: false

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#43]
Setting....

```
// Controls whether the authors email address is displayed in the meta. Needs    config.settings.show_kb_meta" set to true
   
config.settings.show_author_email = false;
```

Authors email address is still shown. Users name is not shown regardless of the option configured.

**Comment by mrvautin** [comment]
Hmm. I assume you have added a name to your user account?

**Comment by mrvautin** [comment]
Assume this is fixed too. Can re-open if needed.
