### ISSUE TITLE
Cannot setup with long TLD

### ISSUE THREAD

**Issue by Wachiwi** [mrvautin/openKB#44]
It seems not possible to setup openKB with TLD's that are longer than 4 chars.

See following example: 

<img width="520" alt="codes" src="https://cloud.githubusercontent.com/assets/4199845/12919450/6703e78a-cf44-11e5-8969-81db45dba002.png">

---

<img width="525" alt="code" src="https://cloud.githubusercontent.com/assets/4199845/12919451/672b8876-cf44-11e5-82fc-ac49d1fc4cca.png">

**Comment by mrvautin** [comment]
OpenKB uses `jqvalidation` for all form validation. It seem the version that ships with openKB an quite out of date and needs updating to the latest version.
