### ISSUE TITLE
Suggest prettier bg classes

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#45]
Suggest the addition of smarter / more in line style - 
Current ones are very dark and not easy to read.
```
{bg-primary}
{bg-warning}
{bg-info}
{bg-success}
{bg-danger}
```

http://getbootstrap.com/css/#helper-classes-backgrounds

![image](https://cloud.githubusercontent.com/assets/13657363/16554867/746788d0-41c9-11e6-8b93-bdd44df7f6ee.png)

**Comment by mrvautin** [comment]
The theme openKB uses is a bit darker than the standard Bootstrap. Is there elements in particular which require are hard to read? If so, which page etc do they appear?

**Comment by thedaftbadger** [comment]
Just used the warn and danger flags and the background was very very dark. Didn't seem to fit the overall default style of openKB
