### ISSUE TITLE
Bug: Missing article info since last update

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#47]
Adding the share icon appears to have removed the following info in the "article details" section

- author name
- author email 
- Permalink

![image](https://cloud.githubusercontent.com/assets/13657363/16651555/a0548180-443c-11e6-8fb0-73c78886e214.png)

`config.settings.show_kb_meta = true;`

**Comment by mrvautin** [comment]
Weird. Obviously that article has an author assigned? 

Does the share link insert the permalink into the email or the id based link? Wanting to know if the permalink variable is being set.

**Comment by thedaftbadger** [comment]
It does seem a little hit and miss, I will investigate

**Comment by thedaftbadger** [comment]
Issue seems to be resolved in latest release.
