### ISSUE TITLE
Issue when dragging image into editor or uploading (Chrome only)

### ISSUE THREAD

**Issue by gallarotti** [mrvautin/openKB#56]
Hi,

I am running open KB in a test environment on Windows 8.1.
When I open the editor on a page inside Chrome 52.0.2743.116 m (64-bit) the site crashes, and I see this error:

```
POST /file/upload_file 200 11.072 ms - -
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\_www\openKB\public\uploads\in
line_files\a4601d960a36e8e345a1f998eb713823'
    at Error (native)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Francesco.Gallar
otti\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! openkb@1.0.5 start: `node app.js`
npm ERR! Exit status 1

```
This works on Firefox.
Since the copy/paste from the clipboard seems to work fine on Chrome, I doubt it's a permission issue.
Also in the C:\_www\openKB\public\uploads\inline_files folder I can see the file being created with the correct name referenced by the markdown image tag - but the file is zero bytes and the app crashes.

Also, uploads in the http://localhost:4444/files work fine on Firefox, but crashes on Chrome:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'C:\_www\openKB\public\uploads\abca1
129e14d2a8f50d783e7a91c2e51'
    at Error (native)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Francesco.Gallar
otti\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! openkb@1.0.5 start: `node app.js`
npm ERR! Exit status 1


```

**Comment by mrvautin** [comment]
This is unusual. I'm not able to replicate the issue when using Google Chrome 52.0.2743.116 (64-bit) on OSX.

The code to upload via paste (Chrome) and drop is the same. It's unusual it works for one and not the other.

I've not tested `openKB` very much (if at all) on Windows. It's possible it's a Node.js path issue.
