### ISSUE TITLE
Suggestions??

### ISSUE THREAD

**Issue by gallarotti** [mrvautin/openKB#58]
What are suggestions for? I tried to submit one when logged out, then I logged back in as admin, and can't seem to find that suggestion anywhere...
I can see it in the data/kb.db, but that's pretty much it

**Comment by mrvautin** [comment]
Suggested articles go into a draft state. After logging in you are still viewing the "public" search where only articles with a published status are able to be searched on. If you click on "Article > Edit" menu you should see your article title with "(SUGGESTION)" on the end.
