### ISSUE TITLE
Feature: SimpleMDE integration

### ISSUE THREAD

**Issue by gallarotti** [mrvautin/openKB#63]
@mrvautin what do you think about replacing the editor / preview with SimpleMDE - https://github.com/NextStepWebs/simplemde-markdown-editor ?
I haven't looked at how you are implementing the drag/drop or copy/paste image uploads. Do you think the new editor could be used still maintaining this awesome functionality you built?

**Comment by thedaftbadger** [comment]
I would back this idea from @gallarotti We've been running openKB for a long time now but to get it outside of our technical departments we would have to be "flexible" with markdown. SimpleMDE would fit this need but we couldn't loose the drag/drop or copy/paste image uploads...... documentation is super fast with it :grin: 

One thing I think we must be mindful of is not to loose the brilliant simplicity of openKB that attracted us to it in the first place :sunglasses:

**Comment by mrvautin** [comment]
I wasn't aware of this editor, it looks really nice.

I'm all for it. It should work straight out the box with the drag and drop unless there is a very weird bug somewhere. 

It would be nice to hook up the editors auto-save feature at some point but that can be done later.

If you submit a PR, I will merge if it's all working good.

**Comment by gallarotti** [comment]
From my preliminary testing with SimpleMDE we would have better preview, cooler interface but we would loose the drag/drop or copy/paste image uploads.
I looked at the existing openKB code and realized that @mrvautin chose to use Bootstrap-Markdown, and with two small changes in the existing code we can add a nice toolbar for bold, italic, headers, links, images, lists, code and quotes.
At the moment I am unable to submit a pull request for this, but the only two changes required are the following.
Inside all the .hbs files that have an editor textarea, just modify the textarea to be:

`                    <textarea id="editor" minlength="5" name="frm_kb_body" data-provide="markdown" data-hidden-buttons="cmdPreview" data-iconlibrary="fa" class="form-control" required>{{{result.kb_body}}}</textarea>`

This will add the toolbar, use font-awesome for the icons, and hide the preview button, since we already have a preview.

Next, in the `styles.css`, today we have:

```
#editor, #preview {
    height: calc(100vh - 110px - 175px);
    overflow: auto;
}
```

We need to change the `#editor` calculation for the height, due to the extra height of the toolbar:

```
#editor {
    height: calc(100vh - 110px - 175px - 47px);
    overflow: auto;
}

#preview {
    height: calc(100vh - 110px - 175px);
    overflow: auto;
}
```

That's it, for me it's working fine... I'll continue to investigate on all the options that are available, but for now this seems to be quite an improvement for just a handful of changes :)

**Comment by mrvautin** [comment]
I'm just playing with your changes now. It looks and works much better in my opinion.

The drag and drop and paste functionality seems to still work for me as I suspected as it should work on any text area element. 

I will test further and commit the changes shortly.

**Comment by gallarotti** [comment]
@mrvautin the drag and drop / copy and paste functionality is part of one of the libraries you used (I forgot is it's Bootstrap's Markdown or Markdown-it, sorry I am not at my computer right now). 
If you swap completely and switch to SimpleMDE you lose that functionality, which is why I preferred to stay with your choices and just play with what those libraries have to offer. 
Good enough for me, I am also investigating a way to add keyboard shortcuts for things like bold, italic, etc.

**Comment by mrvautin** [comment]
Sorry I forgot to update my comment when I figured out it was showing the Bootstrap-markdown editor and not SimpleMDE.

Anyway, I've got it working with SimpleMDE. I'm just cleaning up the code and testing.

**Comment by gallarotti** [comment]
Really? Awesome, looking forward to your next version! I'll have to do some manual merging with my own, but it will be worth it :) thanks for your help!

**Comment by mrvautin** [comment]
Note: The SimpleMDE keyboard shortcuts for bold, italics etc word great already.

**Comment by mrvautin** [comment]
Added a fair few changes in 7bbcd75. 

- Changed to SimpleMDE
- Cleaned up some non used CSS and JS
- Fixed inline attachment to work with SimpleMDE
- A few CSS changes
- Implemented ctrl+s/cmd+s save in edit view
- Fixed the preview live updating (always bothered me) with SimpleMDE

**hopefully nothing is broken...**

**Comment by gallarotti** [comment]
Hey @mrvautin awesome work!
Everything looks good so far.
The only things I changed in my case (and maybe @thedaftbadger would want to do the same for his users) were the definitions of SimpleMDE in `openKB.js` to be:

```
        // setup editors
        var simplemde = new SimpleMDE({
            element: $("#editor")[0],
			autosave: {
				enabled: true,
				uniqueId: "KAD",
				delay: 60000,
			},
            toolbar: ["bold", "italic", "strikethrough", "|", "heading-1", "heading-2", "heading-3", "heading-smaller", "heading-bigger", '|', 'quote', 'unordered-list', 'ordered-list', "code", '|', 'link', 'image', 'table', 'horizontal-rule', '|', 'guide'],
			status: ["autosave", "lines", "words", "cursor"]
        });
```

This way you have a bit more toolbar icons and you have explicitly last autosave time displayed at the bottom. These configs also setup autosave to save every minute instead of the 10 seconds which is by default.
Finally, simply because I don't want confusion for the user, I changed the "editor" view to use monospace fonts by adding font definitions to the `CodeMirror` class inside `style.css`:

```
.CodeMirror {
    height: calc(100vh - 110px - 175px - 70px) !important;
    overflow: auto;
    font-family: monospace;
    font-size: 14px;
}
```

I'll be testing this quite a bit over the next week or so - I will let you know if I see any bugs.
Happy weekend and awesome work!!
// Francesco

**Comment by thedaftbadger** [comment]
@mrvautin @gallarotti Nice work chaps! I will implement a test system in PM2 for the latest round of changes. Liking the new addition of SimpleMDE 😁
