### ISSUE TITLE
New article's editor is not empty

### ISSUE THREAD

**Issue by gallarotti** [mrvautin/openKB#64]
If you edit an article, then save/close, go back to any page and then go to Article/New, the `#editor` textarea will be empty, but the `CodeMirror` will still contain all the text from the last edited article

**Comment by gallarotti** [comment]
Reading the SimpleMDE documentation a bit closer tonight I noticed that the auto save feature requires a uniqueID for each of the instances SimpleMDE in an app:
uniqueId: You must set a unique string identifier so that SimpleMDE can autosave. Something that separates this from other instances of SimpleMDE elsewhere on your website.
I'm our case, we would need different IDs for the edit page, insert page, etc...
Auto save doesn't save in the database. It saves on the client, ready for submission once they click submit. This is useful for when you leave an editor window open for a long time without saving to the database and then something happens and the page reloads and you lost all your changes. 
It has happened to me twice with openKB, so this is a good feature to have, but we need to hook it up correctly. Probably it has to have different IDs not just between edit and insert, but also between different pages being edited, not sure, we need to play around with it.

**Comment by mrvautin** [comment]
What do you think about just auto saving to the DB? Would be pretty easy to setup an timer to fire every X seconds and save the changes to the DB.

**Comment by gallarotti** [comment]
Every time you save to the DB a new entry is made in the database - then at some point (on application restart?) the DB entries with the same ID are merged, haven't really understood how this works yet, maybe you know?
My idea is that we have essentially 3 editors: one for EDIT, one for INSERT and one for SUGGEST. All we need are 3 different IDs, I think. That should resolve this issue. I will play with it later and report.
Also, the fact that you are still using the #preview and `convertTextAreaToMarkdown` is probably not needed any longer. We could just use the SimpleMDE preview feature which has its own rendering (which supports the same features of the markdown-it library you are using). Again something I need to play with...

**Comment by gallarotti** [comment]
Ok, so to fix the issue I opened, I think all we need to do (I did some preliminary testing) is to change the call to the simpleMDE constructor that you have in `openKB.js` to include the name of the page in the autosave configuration, as such:

```
			autosave: {
				enabled: true,
				uniqueId: ("openKB-" + window.location.pathname.split("/").pop()),
				delay: 60000,
			},
```

**Comment by mrvautin** [comment]
Cool. Thanks for looking into it. That solution sounds pretty reasonable.

I will do some tests and commit it to the main branch.

**Comment by gallarotti** [comment]
Cool...
Can you explain how does the saving in the DB actually works?
If I look at the database file in the data folder, every time I save a new document gets added - when does the compacting of the file take place? do you know?

**Comment by mrvautin** [comment]
It adds a new entry for a save but the old one is marked for deletion and its not able to be queried. The compacting etc is all handled by 'nedb'.

**Comment by mrvautin** [comment]
I think this was resolved. If not, happy to reopen.
