### ISSUE TITLE
Image Exporting

### ISSUE THREAD

**Issue by VirtalisNick** [mrvautin/openKB#67]
Good afternoon,

I am currently in the process of sorting out a Knowledge Base for our organisation, and have noticed that openKB is capable of exporting every .md article that exists into one .zip file.

I was wondering if there were a way to set it up so that you could export every single image into a .zip file as well?

Thank you!

Best regards,
Nick Hayden

**Comment by mrvautin** [comment]
The images are stored in a single uploads directory. There is currently no way to export using openKB but you could easily browse the uploads directory and zip it manually.

**Comment by VirtalisNick** [comment]
No problem at all, thank you for your help!
