### ISSUE TITLE
Feature: Image folder variable

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#7]
Add a variable for image URLs to save time when adding images....

`![VPN Connection Windows 7](/images/windows/vpnconnection.png)`

instead of 

`![VPN Connection Windows 7](http://example.com/images/windows/vpnconnection.png)`

Similar to Raneto....

`%image_url%: The base URL of your images folder (public/images)`

**Comment by mrvautin** [comment]
You should be able to use the top (relative path) version. Are you sure it doesn't work?

**Comment by thedaftbadger** [comment]
Sorry, my mistake! I should have checked before hand :see_no_evil: d'oh!
