### ISSUE TITLE
New feature ideas

### ISSUE THREAD

**Issue by mrvautin** [mrvautin/openKB#70]
Received these feature ideas on my personal blog:

1) The integrated user management. I probably will try to hack in google oauth, e.g. via proxy, 
2) We would want to proxy it and that would work better if we could specify a context path ie /openkb
3) In my installation the mermaid charts arent working (not important for us)

**Comment by mrvautin** [comment]
Added 2 in commit: de34957d9ca63467888a09e5e8b3762c624cf156. Hopefully didn't break anything.

**Comment by mrvautin** [comment]
Fixed 3 in commit: 4588200a5dd06822dde17af1d92e80be158b68b8.

**Comment by thedaftbadger** [comment]
Can confirm that mermaid charts doesn't seem to be the best. I suggest we either find a replacement or remove it, I am leaning towards its removal.

**Comment by mrvautin** [comment]
Mermaid charts were fixed in commit: 4588200a5dd06822dde17af1d92e80be158b68b8 but as the minified is > 600kb I've made it an optional feature. It's not usable for public facing apps as users downloading that size file over the Internet is craziness.

**Comment by thedaftbadger** [comment]
I agree it's too large
