### ISSUE TITLE
Ability to redirect urls.

### ISSUE THREAD

**Issue by Collussus** [mrvautin/openKB#74]
Hey there,

While busy with re-factoring articles on a KB running openKB i've run into the problem that external links to the KB from other websites link to articles that don't exist anymore. Is it possible to add the ability to redirect urls to other articles?

That way i can remove articles and still have them go to the article they want.

**Comment by mrvautin** [comment]
There is now way built into openKB currently. 

How many articles do you have? Could you do it through Nginx or similar?

**Comment by Collussus** [comment]
There's about 80 or so articles. I'm working on reducing that to 40. And no, i only have access myself to the knowledgeboard, and would rather not bother the server guy with making 40 redirects.

**Comment by thedaftbadger** [comment]
Can you not leave the original article (the one being removed) live but just with a warning and a hyperlink to the new article?

That is what we would do in there scenarios. To make life easy we also alter the old article title to prefix with [Retired], so we know what to delete in the future.

**Comment by mrvautin** [comment]
Does the solution from @thedaftbadger work for you @Collussus? I'm not sure it would fit into the functionality of `openKB`.

**Comment by mrvautin** [comment]
Closing this unless anyone has anymore input.
