### ISSUE TITLE
Article text spacing

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#8]
Creating blank lines seems a little difficult. I have tried the markdown method of 2 blank spaces followed by a return but it is lost or ignored in OpenKB.

The ability to use blank lines would make formatting text and images a little clearer...

![screenshot_090315_025932_pm](https://cloud.githubusercontent.com/assets/13657363/9660217/630828dc-524c-11e5-8a04-ce9663591236.jpg)

Without blank lines everything just seems crammed together.
Blank lines are recognised in Github?

**Comment by mrvautin** [comment]
Fixed here: 5c03d037fca0f7eb7504305f2ab599af5c4c7459
