### ISSUE TITLE
Version History and Edit Reason

### ISSUE THREAD

**Issue by Zelakto** [mrvautin/openKB#80]
It would be nice if you could see the version history of each article, and maybe even be able to role back to that specified version. Another great feature would that you could set reasons as to why it was edited that certain article. I'm loving openKB so far, keep up the fantastic work!

**Comment by mrvautin** [comment]
Can you elaborate on how this would work? Would there be a button to create a new version?

**Comment by Collussus** [comment]
I'd imagine that this would just save previous iterations of the article as "versions". So each save would be a new version.

**Comment by mrvautin** [comment]
Ok. I'm just thinking how it would all tie in with the ID of the article being the URL (unless permalink set) - eg: `/kb/articleId`. I can see this getting ugly unless well thought through.

Can also see it getting ugly purely with how I use the editor. I press save/CMD+S all the time out of instinct. Not sure if anyone else does this.

**Comment by Collussus** [comment]
This would of course be a feature that is only accessible by users & admins. So you can just run `/kb/articleId/revision`.

And i mean, just see it as how github does it. Even when people push a single forgotten `;` it still pushes a new version.

**Comment by mrvautin** [comment]
Ok. I think the penny just dropped. So then after you are happy with the version, you would push that to the main article ID/permalink in the database to be publicly viewable?

**Comment by Collussus** [comment]
Pretty much, and you keep a history of old revisions so you can revert to old versions if something has gone amiss.

eg: A user who has done a change wrong and another user / admin reverting it.

**Comment by mrvautin** [comment]
Ok. So far I have this:

Each time an article is save another "versioned" article is inserted. When editing an article, it grabs these versioned articles and populate a select input on the right slideout menu of the editor like this:

<img width="440" alt="screen shot 2016-09-16 at 3 33 36 pm" src="https://cloud.githubusercontent.com/assets/299398/18576725/471a1e62-7c23-11e6-9076-f06df77e038b.png">

On change of this select, the article/editor fields are updated with the data from the versioned article. You can then "re-save" those values and essentially rollback a version.

Am I on the right path here?

With the ability to change the version in the editor, would are user still need to view an article `/kb/articleId/revision`?

**Comment by Collussus** [comment]
I would personally prefer an overview of all the versions with the edit reason added to it. As requested in the original post.

Also, i would say that `/kb/articleId/revision` would be a way to "preview" what's in a version for users/admins. EG: Me linking a preview to a head developer of software to verify completeness.

Normal viewers wouldn't need it, it's just for internal use.

**Comment by mrvautin** [comment]
Ok. I will hook up the ability to view revisions to logged in users. It makes sense.

_I would personally prefer an overview of all the versions with the edit reason added to it. As requested in the original post._

Are you able to explain this further? How would you want it UI for such a feature?

**Comment by Collussus** [comment]
I'd think a button on the article to "View versions", and a list of versions like done in the `/articles` with edit reasons added.

Then on the editor have a spot to fill in an edit reason.

**Comment by mrvautin** [comment]
Ok here is another go at it. Let me know what you think.

On the left side of the editor window there is a slide-in menu which is activated by yellow/orange "fork" button (is that obvious or need to change icon/text?):

![image](https://cloud.githubusercontent.com/assets/299398/18606203/e3dcc0f0-7ce7-11e6-873e-0fc94704cf9d.png)

The menu then slides in and looks like below. Here you can add the edit reason (mandatory to save article but may add a settings toggle to add/remove versioning altogether) and below that is the current versions stored. It lists the last 20 versions but this might be too many and need to be taken down a bit?:

![image](https://cloud.githubusercontent.com/assets/299398/18606201/d3007e5c-7ce7-11e6-868f-4fdb72721295.png)

The "Delete" button obviously removed the version and the "Edit" button simply fetches the article version and populates the editor.

I also have setup the `/kb/articleId/revision` view for logged in users too. Any good or need more work?

**Comment by Collussus** [comment]
This looks great. I'll offer more feedback after i take it for a spin :)

**Comment by thedaftbadger** [comment]
Looks like a good solutions for versioning and its simple!

**Comment by Collussus** [comment]
Is there an ETA on when this is getting added?

**Comment by mrvautin** [comment]
There are a lot of code changes and I want to test a little more. Hopefully I get time to push it sometime tonight.
