### ISSUE TITLE
Feature: view all articles

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#83]
I think there should be an option to view all articles when logged in. Currently you can only specify the number of articles shown when in edit mode.

Maybe also look into the possibility of sorting articles via tag as well. A sort of tag cloud?

**Comment by mrvautin** [comment]
Are you referring to the "All" button on `/articles` page?

**Comment by thedaftbadger** [comment]
All button?

**Comment by mrvautin** [comment]
Like this:

![fireshot capture 123 - articles - http___localhost_4444_articles](https://cloud.githubusercontent.com/assets/299398/18507372/3f49f27c-7aaf-11e6-88c0-225439c7c4e4.png)

**Comment by thedaftbadger** [comment]
D'oh I am looking an an older instance.

![giphy](https://cloud.githubusercontent.com/assets/13657363/18507509/8ad9540e-7a68-11e6-8c59-5b4c377c4ef0.gif)


But the filtering by tag / tag cloud is a feature to think about :laughing:

**Comment by mrvautin** [comment]
I understand the tag cloud and I've had that idea before but never got around to doing it. 

How do you imaging the filter will work? Would this commit be something you are thinking: 9f66bf5b0076a03963dd795733a79cd3aea2c3c6. It basically offers live/typeahead searching which gives you results under the search box. There is a screenshot I just updated as an example.
