### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by berndlutz** [mrvautin/openKB#84]
I like openKB. If you like, I could provide german localisation.

A problem with other languages seems to be the arcticle text field. In none english languages, everything is highlighted red.

![bildschirmfoto 2016-09-14 um 12 28 57](https://cloud.githubusercontent.com/assets/224740/18508999/d8d0b068-7a76-11e6-8f54-219459976f57.png)

**Comment by berndlutz** [comment]
Ok, I found a workaround: One can add `spellChecker: false` in public/javascripts/openKB.js on line 95 (see `SimpleMDE(...)`).

Turning spellchecking off would be a great setting.

**Comment by thedaftbadger** [comment]
Suggest maybe adding this into the options page.

**Comment by mrvautin** [comment]
How do you feel about the '/settings' page? Is it getting out of hand with too many options? I was thinking of adding less used/more technical fine tuning setting to the config but for manual editing but not showing in the UI. Some are already like that. Eg: database and sort order.

**Comment by berndlutz** [comment]
Section or tabs on the settings page or a more detailed config file would be great.

**Comment by mrvautin** [comment]
Fixed in: 1abddf8a139ec9bc691d2f09220fab205736c246

**Comment by berndlutz** [comment]
Settings look much cleaner now!
