### ISSUE TITLE
General Localisation

### ISSUE THREAD

**Issue by berndlutz** [mrvautin/openKB#85]
How about localisation with [handlebars.localisation.js](https://gist.github.com/tracend/3261055)?

I could provide a german version or if you like integrate it in total.

**Comment by unixben** [comment]
The gist looks to be client-side localisation.  I've opted to try server-side using [thestonefox/node-translate](https://github.com/thestonefox/node-translate/). I have created a new branch to see what others think: [unixben/openKB:l10n](https://github.com/unixben/openKB/tree/l10n)

**Comment by mrvautin** [comment]
Creating localisation is a decent amount of work. I've used the `i18n-2` module in another project ([adminMongo](https://github.com/mrvautin/adminMongo)) successfully. 

It seems better as it does file checking, generates english files etc. Maybe someone wants to check that project out and add it to `openKB`? I simply don't have the time to manually add in the references to i18n in all the files.

**Comment by unixben** [comment]
Yes, it will take time. i18n-2 looks good and will definitely kick-start the English internationalisation. I've started work on it now since I have a need for it myself.

**Comment by unixben** [comment]
Updated my localisation tree [unixben/openKB/tree/l10n](https://github.com/unixben/openKB/tree/l10n) with i18n-2 for review.

**Comment by mrvautin** [comment]
Had a quick check and it looks good. If you submit a PR I will merge it into `openKB`.

Sometimes changes like this require some use over time by real users to find all the cheeky localisation phrases. Most are normally found by people start translating into other languages.

**Comment by mrvautin** [comment]
FYI @berndlutz.
