### ISSUE TITLE
Upgrading Issues

### ISSUE THREAD

**Issue by Zelakto** [mrvautin/openKB#89]
After installing openKB on a development site for testing purposes and importing our production databases to our testing site, all the articles result in a 404 error. However on the main page it has all the featured articles and top articles. ![](https://i.zelakto.tv/EW8afTx.png) The `/articles` page is also completely empty, and the edit list is not working (`/edit/wFHm5ZrTbIcuyGiA` results in a 404).

**Comment by mrvautin** [comment]
Are you able to give more information? What database type are you using?

Are you using the latest `openKB` with article versioning?

**Comment by Zelakto** [comment]
Derp, sorry about that. I'm using the latest build as of last night. For the databases, i'm using the standard `users.db`, `kb.db`, etc. Hope this helps!

**Comment by mrvautin** [comment]
Hmm. I'm not sure I tested thoroughly enough on embedded databases. I will have a look when I get a second. It's relating to the version changes. 

You will have to roll back until I can have a look and fix it.

**Comment by Zelakto** [comment]
I'm going to reopen this issue, since after importing all my articles, I still am getting this error. After some testing, it seems like the issue is with versioning, because if I turn versioning on and edit and article, it saves fine, but if I were to edit it again, it says an article already exists with that permalink. If I turn off versioning and edit another article twice, it works perfectly. I hope this helps!
