### ISSUE TITLE
Can't get permalinks to work when running on a weird port

### ISSUE THREAD

**Issue by pricecomstock** [mrvautin/openKB#90]
Hello,

My ISP blocks port 80, so naturally I used a port I had already opened (for Mumble) but was no longer in use, 64738. The permalinks for articles show up as my.domain/kb/article_title. I need them to link to my.domain:64738/kb/article_title. Is there some way to do this?

I could possibly also switch from subdomains to subdirectories and use some DNS and Nginx trickery to get this to work, but the ability to modify the permalinks would be my preferred solution.

Thanks for the great software!

**Comment by mrvautin** [comment]
In this case the ideal and easiest solution would be to setup Nginx or Apache and proxy to your port.

There is no ability to set the base url right now.
