### ISSUE TITLE
Window Title never changes

### ISSUE THREAD

**Issue by vstiebe** [mrvautin/openKB#92]
The title used on the first article version is always on the window/tab title even after changing the article title.

**Comment by mrvautin** [comment]
I assume you means the HTML title tags? If so, this is due to the SEO Title value in the editor (right menu activated with the cog icon). This value is not changed upon changing the title of the article as sometimes (often?) you would want these to be different.

**Comment by vstiebe** [comment]
Thanks for pointing that out.
