### ISSUE TITLE
Show author email doesn't work

### ISSUE THREAD

**Issue by Alvaroctal** [mrvautin/openKB#95]
Hi, 

Firstly, congrats for this minimalist piece of software, this was exactly what I was looking for, will keep an eye on this project .

I found the following bug, trying to hide the authors email at the end of each post found the option:

`Settings > Article > Show author email` doesn't seems to be working, of course, hiding `meta data` does the job, but I guess that not the idea.

thanks in advance.

**Comment by mrvautin** [comment]
It seems to work for me in the latest version. Are you able to provide more details?

**Comment by Alvaroctal** [comment]
Ok, after some testing I almost sure this is the reason:

The default view checks it, and in fact it works fine as you said.
https://github.com/mrvautin/openKB/blob/9312d731be6f201491723cf18be843180bd2c030/views/kb.hbs#L95

But, when I opened the issue I was using twitter theme, which apparently does the same check, but it shows always the author's email:
https://github.com/mrvautin/openKB/blob/9312d731be6f201491723cf18be843180bd2c030/public/themes/twitter/views/kb.hbs#L122

**Comment by mrvautin** [comment]
Oh ok. The Twitter theme will need updating. The line you can add to the Twitter theme is: https://github.com/mrvautin/openKB/blob/9312d731be6f201491723cf18be843180bd2c030/views/kb.hbs#L77
