### ISSUE TITLE
Validating or Generating a permalink causes edits to be lost

### ISSUE THREAD

**Issue by unixben** [mrvautin/openKB#96]
While creating a new article or editing an existing one, and with unsaved edits, if you click the "Generate" button to generate a permalink, the contents of the editor are lost.

Additionally, if you enter any permalink value and click the "Validate" button, the contents of the editor are lost.

Using Chrome 53.0.2785.143 (Official Build) (64-bit) on MacOS 10.12.

**Comment by JonathanKryza** [comment]
I have the same issue. All content is lost after selecting "generate"

Using Heroku.
